modLoader="javafml"
loaderVersion="[32,)"
license="MIT License"
issueTrackerURL="https://github.com/anthxnymc/hexforged/issues" #optional

[[mods]]
    displayName="Hexforged"
    modId="hexforged"
    version="${file.jarVersion}"
    displayURL="https://github.com/anthxnymc/hexforged"
    logoFile="logo.png"
    credits="Anthxny"
    authors="Anthxny"
    description="Hybrid magic-tech mod."


[[dependencies.hexforged]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hexforged]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hexforged]]
   modId="curios"
   mandatory=true
   versionRange="[1.18.1-5.0.4.2,)"
   ordering="AFTER"
   side="BOTH"

[[dependencies.hexforged]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.c,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.hexforged]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.1.40,)"
    ordering="AFTER"
    side="BOTH"